version: '3.8'

services:
  web:
    build: ./src
    image: dcrapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    depends_on:
      - db

  db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres